### PR TITLE
Add mnestix-browser repository

### PR DESCRIPTION
**Pull request by GailMelanie**
Added mnestix-browser repository through otterdog.

### CODE REVIEW

**Review by netomi — APPROVED** [review]
LGTM, I added the project leads as reviewers. Once approved you can merge yourself by adding `/otterdog merge` as comment

**Comment by hofermo** [comment]
We spoke to the Project Leads directly, as they have not yet connected their GitHub Account to their Eclipse Account.
They agreed we can merge.

**Comment by hofermo** [comment]
@netomi thank you :)

**Pull request merged**
